queries:
  - "electrical workforce training funding Illinois 2025"
  - "IBEW apprenticeship program grants Illinois"
  - "electrical training vendor contracts Chicago"
  - "workforce development electrical trade funding"
  - "electrical apprenticeship funding misuse investigation"
  - "Department of Labor electrical training grants"
  - "Illinois electrical training program oversight"

watchlist:
  - name: "Illinois Department of Commerce and Economic Opportunity"
    url: "https://dceo.illinois.gov"
  - name: "U.S. Department of Labor Employment and Training Administration"
    url: "https://www.dol.gov/eta"
  - name: "IBEW Local 134"
    url: "https://www.ibew134.org"
  - name: "Chicago Electrical Joint Apprenticeship and Training Committee"
    url: ""
  - name: "National Electrical Contractors Association Illinois"
    url: ""

